name: Release Creation via Badger Den

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      
      - uses: actions/checkout@v3
        if: "github.event.release.prerelease"
      - name: Use Node.js ${{ matrix.node-version }}
        if: "github.event.release.prerelease"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        if: "github.event.release.prerelease"
      - run: npm run build
        if: "github.event.release.prerelease"
      - run: npm run example-module -- --config-version "${{github.event.release.tag_name}}"
        if: "github.event.release.prerelease"

      # Create a release for this specific version
      - name: Update Release with Files
        if: "github.event.release.prerelease"
        id: create_version_release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './src/demo-module/built-altered-demo/altered-demo/module.json, ./src/demo-module/built-altered-demo/altered-demo-${{github.event.release.tag_name}}.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
